### ISSUE TITLE
Use netlify.toml to automate the build process and use CDN for static files

### ISSUE THREAD

**Issue by davidpelayo** [davidpelayo/www#5]
Instead of setting up webhooks built-in with the docker image capabilities in repo, I'll be moving to netlify as soon as the guys update the supported version of hugo to at least 0.30.

See the issue [here](https://github.com/netlify/build-image/issues/93).

**Comment by bep** [comment]
>I'll be moving to netlify as soon as the guys update the supported version of hugo to at least 0.30.

You can easily use newer Hugo version by setting `HUGO_VERSION` env var in console or netlify.toml, see

https://github.com/gohugoio/hugoDocs/blob/master/netlify.toml

**Comment by davidpelayo** [comment]
@bep ok, I'll try and see. Didn't want to spend the time in the first place not being sure if it would work.

Thanks!

**Comment by davidpelayo** [comment]
Linked to Netlify. Therefore, closing ticket.
